### PR TITLE
Activate ci

### LINKED ISSUE #14: Setup Travis for CI
### Description

Create a `travis.yml` file which runs our CI before deploying the site on PRs and master branches. 

**Why this is valuable:**

This will help developers make sure they pass all tests and linting before the site is deployed.

### Acceptance Criteria

- [ ] Prettier and flow are run in checks
- [ ] Checks are run before deployment
- [ ] Status of checks show up in github
- [ ] Travis build badge is present in readme

### PR DESCRIPTION
**Pull request by coilysiren**
### Proposed changes

- add a travis config
- commit the results of `npm run format`
- add a travis readme badge

### Acceptance criteria

- [x] Prettier and flow are run in checks
- [x] Checks are run before deployment (not accomplished directly, see _Requested feedback_ below)
- [x] Status of checks show up in github
- [x] Travis build badge is present in readme

### Requested feedback

I suggest we implement *Checks are run before deployment* via github settings, like so:

- Go to this url https://github.com/WriteSpeakCode/writespeakcode.com/settings/branches
- Add a rule for `production` if you haven't already (edit: I think you have ^^)
image 
image
- And require the travis check be passing 
image

### CODE REVIEW

**Comment by coilysiren** [comment]
Tests are failing pending a release that includes https://github.com/pillarjs/finalhandler/issues/26, due to https://www.npmjs.com/advisories/836

Also I need to fix my local gpg config to fix the `Unverified` badge on my commits ^^

EDIT: both these problems are fixed now 👍

**Comment by coilysiren** [comment]
I'm not sure that we actually want to fail builds on low severity audit reports? That's a recipe for the build failing for all kinds of reasons outside of our control. I'll think about this 🤔

**Comment by coilysiren** [comment]
Ready for review 👀

**Review by deweydell — DISMISSED** [review]
Lynn this is so great! Thanks for making the first PR. Feel free to merge this. 

RE: The open acceptance criteria I'll add the branch protection rules. 

Do you know which one of these travis items I should select?
Screen Shot 2019-05-07 at 1 35 25 PM

Also -- do you think we should remove `npm audit` from CI?

**Comment by coilysiren** [comment]
> Also -- do you think we should remove `npm audit` from CI?

I have a bunch of thoughts here ✨ So (...)

I think that for the most part its going to be noisy on ci. Noisy here means: that most people won't care about its output, even though its outputting a bunch of stuff. I don't think we would ever want ci to fail on `npm audit --audit-level=low`, I feel like that would end up blocking a bunch of people based on things they didn't actually change. If we find that a lot of the newer developers are seeing the `npm audit` output in ci and thinking that its a problem they should solve (or a problem in their PR), then we should remove it at that point.

**Comment by coilysiren** [comment]
> Do you know which one of these travis items I should select?

IMO, these two:

- Travis CI - Branch
- Travis CI - Pull Request

@deweydell

**Comment by deweydell** [comment]
I agree with you that running the audit might become a blocker for folks. I will try to think of a better way to manage audits. This is just how my team automates it so I'm open to suggestions.

**Comment by coilysiren** [comment]
image

@deweydell the github settings don't give me auth to merge (even with the approval)

**Comment by deweydell** [comment]
@lynncyrin I added our team to the list able to push to production. Are you able to merge now?

**Comment by coilysiren** [comment]
I've got merge access now yea! I'm pulling master into this branch now

**Comment by coilysiren** [comment]
Pulling it master made the tests go red, so I'll work on fixing that now 👍

**Review by deweydell — APPROVED** [review]
🚀

**Pull request merged**
