### PR TITLE
Have prettier ignore content dirs

### PR DESCRIPTION
**Pull request by coilysiren**
to fix failed builds from the CMS, like https://github.com/WriteSpeakCode/writespeakcode.com/pull/56

### CODE REVIEW

**Comment by coilysiren** [comment]
I merged this into https://github.com/WriteSpeakCode/writespeakcode.com/pull/55 to double check that it works on ci ^^

**Comment by deweydell** [comment]
Is there anyway to ignore this besides prettierignore? I'm wondering because if choose to add content manually, I still would like prettier to format my code while I'm developing.

**Review by deweydell — APPROVED** [review]
I'm fine to merge this now so the speaker PRs build successfully, but would like to revisit a way prettier can work when manually editing content files.

**Comment by coilysiren** [comment]
I'll write up an issue about follow-up here!

**Comment by coilysiren** [comment]
issue => https://github.com/WriteSpeakCode/writespeakcode.com/issues/61

**Pull request merged**
